sudo: required
dist: trusty
language: node_js
git:
  depth: 10
node_js:
  - "6"
env:
  matrix:
    - TWBS_TEST=core
    - TWBS_TEST=validate-html
    - TWBS_TEST=browserstack
before_install:
  - "export TRAVIS_COMMIT_MSG=\"$(git log --format=%B --no-merges -n 1)\""
  - echo "$TRAVIS_COMMIT_MSG" | grep '\[skip validator\]'; export TWBS_DO_VALIDATOR=$?; true
  - echo "$TRAVIS_COMMIT_MSG" | grep '\[skip browserstack\]'; export TWBS_DO_BROWSERSTACK=$?; true
install:
  - bundle install --deployment --jobs=3 --retry=3
  - npm install
matrix:
  fast_finish: true
cache:
  directories:
    - node_modules
    - vendor/bundle
